package com.youmeandmyself.ai.chat

import com.intellij.openapi.Disposable
import com.intellij.openapi.project.Project
import com.intellij.ui.jcef.JBCefBrowser
import com.youmeandmyself.ai.bridge.CrossPanelBridge
import com.youmeandmyself.ai.chat.bridge.BridgeDispatcher
import com.youmeandmyself.ai.chat.bridge.JcefBridgeTransport
import com.youmeandmyself.ai.chat.context.LocalSummaryStoreProvider
import com.youmeandmyself.ai.chat.orchestrator.ChatOrchestrator
import com.youmeandmyself.ai.providers.parsing.ui.CorrectionFlowHelper
import com.youmeandmyself.ai.providers.parsing.ui.FormatHintStorageImpl
import com.youmeandmyself.dev.Dev
import com.youmeandmyself.storage.LocalStorageFacade
import java.awt.BorderLayout
import javax.swing.JPanel

/**
 * React-based chat panel — serves the built React app in JCEF.
 *
 * ## What This Class Does
 *
 * 1. Creates a JCEF browser instance
 * 2. Loads the single-file React HTML (built by Vite, inlined into resources)
 * 3. Wires the three-layer bridge: Transport → Dispatcher → Orchestrator
 * 4. Provides a Swing JPanel for embedding in IntelliJ's tool window
 *
 * ## What This Class Does NOT Do
 *
 * - Render any UI (React handles all rendering)
 * - Process chat logic (ChatOrchestrator handles all business logic)
 * - Manage conversations (ChatOrchestrator handles conversation state)
 * - Build prompts (ContextAssembler handles prompt construction)
 *
 * ## Architecture
 *
 * ```
 * ReactChatPanel (this class — thin Swing shell)
 *     └── JBCefBrowser (JCEF instance, renders React app)
 *         └── JcefBridgeTransport (JS↔Kotlin wire layer)
 *             └── BridgeDispatcher (routes commands to orchestrator)
 *                 └── ChatOrchestrator (all business logic)
 * ```
 *
 * ## HTML Loading
 *
 * The React app is built into a single HTML file by Vite + vite-plugin-singlefile.
 * Gradle copies it to `resources/react-chat/index.html` during the build.
 * This class reads it at startup and loads it via `browser.loadHTML()`.
 *
 * ## Toggle Between Legacy and React
 *
 * The build system or a dev flag controls which panel is used.
 * Both panels wire to the same ChatOrchestrator — they're interchangeable
 * from the backend's perspective.
 *
 * @param project The IntelliJ project context
 */
class ReactChatPanel(private val project: Project) : Disposable {

    private val log = Dev.logger(ReactChatPanel::class.java)

    /** Root Swing panel — embed this in the IntelliJ tool window. */
    val root = JPanel(BorderLayout())

    /** JCEF browser instance that renders the React app. */
    private val browser: JBCefBrowser = JBCefBrowser()

    /** Correction flow helper — one per tab to avoid cross-tab conflicts. */
    private val correctionHelper: CorrectionFlowHelper by lazy {
        CorrectionFlowHelper(
            project = project,
            storageFacade = LocalStorageFacade.getInstance(project),
            hintStorage = FormatHintStorageImpl.getInstance()
        )
    }

    /** The orchestrator — all business logic lives here. */
    private val orchestrator: ChatOrchestrator by lazy {
        ChatOrchestrator.create(
            project = project,
            correctionHelper = correctionHelper,
            summaryStore = LocalSummaryStoreProvider(project)
        )
    }

    /** Bridge dispatcher — routes commands from React to the orchestrator. */
    private val dispatcher: BridgeDispatcher by lazy {
        BridgeDispatcher(
            project = project,
            orchestrator = orchestrator,
            sendEvent = { json -> transport.sendEventToFrontend(json) }
        )
    }

    /** JCEF transport — wires the browser's JS↔Kotlin communication. */
    private val transport: JcefBridgeTransport by lazy {
        JcefBridgeTransport(
            browser = browser,
            dispatcher = dispatcher
        )
    }

    init {
        Dev.info(log, "react_panel.init", "start" to true)

        // Add the JCEF browser to the Swing panel
        root.add(browser.component, BorderLayout.CENTER)

        // Force lazy init of the transport (registers the JCEF query handler
        // BEFORE we load the HTML, so the handler is ready when React starts)
        @Suppress("UNUSED_VARIABLE")
        val unused = transport

        // Register with CrossPanelBridge so Library "Continue chat" can reach React
        CrossPanelBridge.getInstance(project).registerChatDispatcher(dispatcher)
        Dev.info(log, "react_panel.cross_panel_bridge", "registered" to true)

        // Load the React app HTML
        loadReactHtml()

        Dev.info(log, "react_panel.init", "complete" to true)
    }

    /**
     * Load the built React HTML into the JCEF browser.
     *
     * Reads the single-file HTML from the plugin's resources. This file
     * is generated by `npm run build` in the react-frontend project and
     * copied to resources by Gradle.
     *
     * Falls back to an error page if the resource is missing (build step
     * was skipped or failed).
     */
    private fun loadReactHtml() {
        val htmlResource = javaClass.getResourceAsStream("/react-chat/index.html")

        if (htmlResource != null) {
            val html = htmlResource.bufferedReader().use { it.readText() }
            browser.loadHTML(html)
            Dev.info(log, "react_panel.html_loaded", "length" to html.length)
        } else {
            // Resource not found — build step was likely skipped.
            // Show a helpful error instead of a blank page.
            val errorHtml = """
                <!DOCTYPE html>
                <html>
                <body style="padding: 20px; font-family: sans-serif; color: #d4d4d4; background: #1e1e1e;">
                    <h2>React UI Not Built</h2>
                    <p>The React chat interface hasn't been built yet.</p>
                    <p>Run <code>cd react-frontend && npm install && npm run build</code> to build it,
                       then restart the IDE.</p>
                    <p>The built HTML will be placed at <code>src/main/resources/react-chat/index.html</code>.</p>
                </body>
                </html>
            """.trimIndent()
            browser.loadHTML(errorHtml)
            Dev.warn(log, "react_panel.html_not_found", null,
                "expected" to "/react-chat/index.html"
            )
        }
    }

    /**
     * Get the orchestrator's conversation ID (for tab management).
     */
    fun getConversationId(): String? = orchestrator.getConversationId()

    /**
     * Set the orchestrator's conversation ID (for tab switching).
     */
    fun setConversationId(conversationId: String?) {
        orchestrator.setConversation(conversationId)
    }

    // ── Disposable ───────────────────────────────────────────────────

    /**
     * Clean up all resources: JCEF transport, browser, and any coroutine scopes.
     *
     * Called when the tool window tab is closed or the project is closed.
     */
    override fun dispose() {
        CrossPanelBridge.getInstance(project).unregisterChatDispatcher()
        transport.dispose()
        browser.dispose()
        Dev.info(log, "react_panel.disposed", "cross_panel_bridge" to "unregistered")
    }
}
