/**
 * Metrics Module — Type Definitions
 *
 * All metrics-related TypeScript types live here. These are the data
 * structures that flow through the entire React metrics layer:
 *
 * ```
 * UPDATE_METRICS event (from Kotlin)
 *     │
 *     ▼
 * MetricsSnapshot (one exchange's metrics)
 *     │
 *     ├── stored as TabMetricsState.lastExchange
 *     └── fed into accumulate() → updates TabMetricsState.session
 *                                      │
 *                                      ▼
 *                              MetricsAccumulator (running totals)
 *                                      │
 *                                      ▼
 *                              MetricsBar.tsx renders both
 * ```
 *
 * ## Design Principles
 *
 * - Nullable everywhere: Not all providers report all token fields.
 *   Null means "not available" — the UI hides that element gracefully.
 *
 * - Session-scoped accumulator: Resets when the tab is closed or cleared.
 *   Historical aggregation comes from SQLite queries (post-launch).
 *
 * - Per-model breakdown: The accumulator tracks totals per model so the
 *   Metrics Tab (post-launch) can show a model comparison chart without
 *   any additional backend queries for session data.
 *
 * @see accumulator.ts — Pure functions that operate on these types
 * @see MetricsBar.tsx — UI component that renders these types
 * @see useBridge.ts — Hook that manages TabMetricsState per tab
 */

// ═══════════════════════════════════════════════════════════════════════
//  SNAPSHOT — One Exchange's Metrics
// ═══════════════════════════════════════════════════════════════════════

/**
 * Token usage snapshot from a single AI exchange.
 *
 * Created from each UPDATE_METRICS bridge event and also from
 * HistoryMessageDto when seeding the accumulator from conversation
 * history on tab restore.
 *
 * Every field is nullable because different providers report different
 * subsets of token data. The accumulator and display layer treat null
 * as "skip this field."
 */
export interface MetricsSnapshot {
    /** Model identifier (e.g., "gpt-4o", "gemini-2.5-flash"). */
    model: string | null;

    /** Input tokens sent to the model. */
    promptTokens: number | null;

    /** Output tokens generated by the model. */
    completionTokens: number | null;

    /** Provider-reported total tokens. */
    totalTokens: number | null;

    /**
     * Model's maximum context window in tokens.
     * Resolved from AiProfile.contextWindowSize or DefaultContextWindows.
     * Null if unknown — fill bar is hidden.
     */
    contextWindowSize: number | null;

    /**
     * Wall-clock time for the AI call in milliseconds.
     * Null if timing wasn't captured.
     */
    responseTimeMs: number | null;
}

// ═══════════════════════════════════════════════════════════════════════
//  ACCUMULATOR — Session Running Totals
// ═══════════════════════════════════════════════════════════════════════

/**
 * Per-model token breakdown within the session accumulator.
 *
 * Enables the Metrics Tab (post-launch) to show a model comparison
 * chart without additional backend queries for session data.
 */
export interface ModelBreakdown {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
    exchangeCount: number;
}

/**
 * Running totals for a tab's session.
 *
 * Accumulated from MetricsSnapshot values via the accumulate() function.
 * Resets when the tab is closed or chat is cleared. Historical
 * aggregation (across sessions) comes from SQLite queries (post-launch).
 *
 * ## Null Handling
 *
 * The accumulator adds non-null values and skips nulls. This means:
 * - If 3 of 5 exchanges report promptTokens, totalPromptTokens is
 *   the sum of those 3 (not 5).
 * - exchangeCount always increments (tracks how many snapshots were fed in).
 * - byModel tracks per-model subtotals for the same reason.
 */
export interface MetricsAccumulator {
    /** Sum of all non-null promptTokens values. */
    totalPromptTokens: number;

    /** Sum of all non-null completionTokens values. */
    totalCompletionTokens: number;

    /** Sum of all non-null totalTokens values. */
    totalTokens: number;

    /** Number of exchanges accumulated (always increments). */
    exchangeCount: number;

    /**
     * Per-model breakdown within this session.
     *
     * Key is the model name (e.g., "gpt-4o"). Entries are created
     * on first encounter and updated on subsequent exchanges.
     * Exchanges with null model are grouped under the key "__unknown__".
     *
     * Uses a plain object (Record) instead of Map for JSON serializability
     * and simpler React state updates.
     */
    byModel: Record<string, ModelBreakdown>;
}

// ═══════════════════════════════════════════════════════════════════════
//  TAB STATE — Per-Tab Metrics Container
// ═══════════════════════════════════════════════════════════════════════

/**
 * Per-tab metrics state: last exchange snapshot + session accumulator.
 *
 * Always initialized (never null) — starts with null lastExchange and
 * an empty accumulator. Stored in TabData.metricsState.
 *
 * ## Lifecycle
 *
 * - Created fresh when a tab is created (createTab())
 * - Updated on every UPDATE_METRICS event (snapshot + accumulate)
 * - Seeded from conversation history on tab restore (accumulate only,
 *   lastExchange stays null until a new live exchange arrives)
 * - Reset when chat is cleared (CONVERSATION_CLEARED)
 *
 * @see useBridge.ts — manages this state per tab
 * @see MetricsBar.tsx — renders this state
 */
export interface TabMetricsState {
    /**
     * Most recent exchange metrics.
     *
     * Drives the "LAST" display mode in MetricsBar. Null until the
     * first live exchange arrives in this session (not set from history
     * seeding — historical data only feeds the accumulator).
     */
    lastExchange: MetricsSnapshot | null;

    /**
     * Running totals for this tab's session.
     *
     * Drives the "SESSION" display mode in MetricsBar. Starts at zero,
     * grows with each exchange. Includes both live exchanges and
     * history-seeded data (so reopened conversations show cumulative
     * totals from the start).
     */
    session: MetricsAccumulator;
}