package com.youmeandmyself.ai.metrics

import kotlinx.serialization.Serializable

/**
 * Atomic metrics record for a single AI exchange.
 *
 * ## Purpose
 *
 * Every AI call — chat or summary — produces exactly one MetricsRecord.
 * This is the foundational unit for all metrics aggregation. Everything
 * else (session totals, per-model breakdown, per-provider charts,
 * company-wide analytics) is derived from these records.
 *
 * ## Design Principles
 *
 * - **All fields present from day one.** Company tier fields (userId,
 *   projectId) are nullable and unused at Individual launch, but their
 *   columns exist in SQLite so we never need a migration script.
 *   (JSONL is truth, SQLite is a rebuildable index — schema changes go
 *   directly in CREATE TABLE.)
 *
 * - **Measurement ≠ Valuation.** This record holds token counts only.
 *   Converting tokens to cost is the Pricing Module's job (post-launch).
 *   No cost fields here, ever.
 *
 * - **Nullable token counts.** Not all providers report all three counts.
 *   Some only report totalTokens, some skip completionTokens. Nulls are
 *   fine — the accumulator and display layer handle them gracefully.
 *
 * - **contextWindowSize is a snapshot.** It captures the model's max
 *   context as configured at the time of the call. If the user later
 *   changes the profile's context window setting, historical records
 *   keep the value that was active when they were created.
 *
 * ## Aggregation Dimensions
 *
 * This record supports roll-up along any combination of:
 * - Per exchange (exchangeId)
 * - Per tab (tabId — session only)
 * - Per conversation (conversationId)
 * - Per model (model)
 * - Per provider (providerId)
 * - Per provider × model
 * - Per purpose (CHAT, FILE_SUMMARY, etc.)
 * - Per time bucket (timestampMs)
 * - Per user (userId — Company tier)
 * - Per project (projectId — Company tier)
 *
 * Aggregations are computed on read, never stored separately.
 *
 * ## Storage
 *
 * Written to two locations:
 * 1. SQLite `metrics` table — for fast aggregation queries
 * 2. JSONL exchange record — embedded as a `metrics` field for
 *    source-of-truth rebuild capability
 *
 * @see com.youmeandmyself.ai.metrics.MetricsService — writes these records
 * @see com.youmeandmyself.ai.metrics.DefaultContextWindows — provides default contextWindowSize
 */
@Serializable
data class MetricsRecord(

    // ── Identity ──────────────────────────────────────────────────────

    /** Links to the chat exchange (chat_exchanges.id). Primary key in the metrics table. */
    val exchangeId: String,

    /** Groups exchanges into conversations. Required — every exchange belongs to a conversation. */
    val conversationId: String,

    /**
     * UI tab identifier. Session-only — not meaningful for historical queries.
     * Null for summary exchanges (which have no visible tab).
     */
    val tabId: String? = null,

    // ── What was called ───────────────────────────────────────────────

    /** AI profile ID (e.g., the UUID from AiProfile.id). */
    val providerId: String,

    /** Human-friendly profile name (e.g., "My Gemini"). For display in metrics charts. */
    val providerLabel: String,

    /** API protocol used: OPENAI_COMPAT, GEMINI, or CUSTOM. */
    val protocol: String,

    /**
     * Model identifier as reported by the provider (e.g., "gpt-4o", "gemini-2.5-flash").
     * Nullable because some providers don't report the model or the profile might not
     * have one configured.
     */
    val model: String? = null,

    // ── Token counts ──────────────────────────────────────────────────

    /** Input tokens sent to the model. Null if the provider didn't report this. */
    val promptTokens: Int? = null,

    /** Output tokens generated by the model. Null if the provider didn't report this. */
    val completionTokens: Int? = null,

    /**
     * Provider-reported total tokens. May differ from promptTokens + completionTokens
     * (some providers include system tokens, caching, etc. in the total).
     * Null if the provider didn't report this.
     */
    val totalTokens: Int? = null,

    // ── Context ───────────────────────────────────────────────────────

    /**
     * Model's maximum context window in tokens, as configured at call time.
     * Sourced from AiProfile.contextWindowSize (user override) or
     * DefaultContextWindows.lookup() (built-in defaults).
     * Null if unknown — the fill bar is simply hidden in that case.
     */
    val contextWindowSize: Int? = null,

    /**
     * What this exchange was for: CHAT, FILE_SUMMARY, METHOD_SUMMARY,
     * CLASS_SUMMARY, MODULE_SUMMARY, PROJECT_SUMMARY.
     * Stored as a string (not enum) to avoid coupling to ExchangePurpose
     * and to support future purpose types without changing this class.
     */
    val purpose: String = "CHAT",

    // ── Time ──────────────────────────────────────────────────────────

    /** Unix epoch milliseconds when this exchange was recorded. */
    val timestampMs: Long,

    /**
     * Wall-clock time for the AI call in milliseconds.
     * Measured from request send to response complete in the orchestrator.
     * Null if timing wasn't captured (e.g., legacy records, background summaries).
     */
    val responseTimeMs: Long? = null,

    // ── Company tier (Phase 6) ────────────────────────────────────────

    /**
     * Developer identifier for company-tier per-user analytics.
     * Null in Individual tier — populated when Company tier ships (Phase 6).
     * Never exposed in individual-tier UI.
     */
    val userId: String? = null,

    /**
     * Project identifier for cross-project aggregation.
     * Null at launch — populated when Company tier ships (Phase 6).
     * Individual tier has a single implicit project.
     */
    val projectId: String? = null,

    // ── Per-block token estimates (Phase 1 — RequestBlocks) ──────────
    //
    // Estimated token counts for each section of the structured request.
    // These are ESTIMATES (content.length / 4 heuristic), not provider-reported.
    // The provider-reported promptTokens/completionTokens/totalTokens above
    // remain the authoritative totals.
    //
    // Purpose: per-block breakdown for the stacked fill bar (Phase 4 UI)
    // and context cost visibility.

    /** Estimated tokens for the system prompt (assistant profile). Null if no profile. */
    val profileTokens: Int? = null,

    /** Estimated tokens for conversation history (compacted + verbatim). */
    val historyTokens: Int? = null,

    /** Estimated tokens for the context block (summaries + raw + other). */
    val contextTokens: Int? = null,

    /** Estimated tokens for the user's message. */
    val messageTokens: Int? = null
)