/**
 * Scrollable message list component.
 *
 * ## 4B Changes
 *
 * - Expand/collapse toggle (▾/▸) on each assistant message header.
 *   Collapsed messages show only the header row with a content preview
 *   (~60 chars). Content, correction buttons, and timestamp are hidden.
 * - Collapse All / Expand All toolbar button above the message list.
 *   Only visible when 2+ assistant messages exist. Toggles based on
 *   whether any messages are currently collapsed.
 * - collapsedIds comes from useBridge (per-tab TabData.collapsedIds),
 *   so collapse state survives tab switching within a session.
 *   Resets on IDE restart (not persisted to backend).
 *
 * ## R5 Changes
 *
 * - Code block star button REMOVED — star belongs on the response level only.
 * - Bookmark ribbon icon ADDED to code block headers. Clicking bookmarks the
 *   entire exchange that contains the code block. The icon is an SVG ribbon
 *   matching the design from the R5 spec.
 * - Code block actions now always right-aligned (margin-left: auto in CSS)
 *   regardless of whether a language label is present.
 * - Scroll position restore: when tab switches or history loads, the list
 *   scrolls to the saved position from TabData.scrollPosition.
 *
 * ## R4 Changes (preserved)
 *
 * - Star (favourite) toggle button on assistant messages (exchange-level).
 * - Scroll-to-bottom floating button.
 * - Scroll position tracking for per-tab persistence.
 *
 * ## Markdown Rendering (R2)
 *
 * Assistant messages are rendered through markdown-it with highlight.js.
 * dangerouslySetInnerHTML is safe because markdown-it html: false prevents injection.
 *
 * ## Code Copy Button (R2)
 *
 * Event delegation on the container. Clicks on .ymm-code-copy read base64 code
 * from data-code attribute on the parent .ymm-code-block.
 */
import { useEffect, useRef, useCallback } from "react";
import type { ChatMessage } from "../hooks/useBridge";
import { renderMarkdown } from "../rendering/markdownRenderer";
import { renderMermaidBlocks } from "../rendering/mermaidRenderer";
import SystemMessage from "./SystemMessage";
import ThinkingIndicator from "./ThinkingIndicator";
import { log } from "../utils/log";

interface MessageListProps {
    messages: ChatMessage[];
    isThinking: boolean;
    isScrolledUp: boolean;
    scrollPosition: number;
    /** 4B: Set of collapsed assistant message IDs, managed by useBridge per-tab. */
    collapsedIds: Set<string>;
    onConfirmCorrection: () => void;
    onRequestCorrection: () => void;
    onToggleStar: (exchangeId: string) => void;
    onBookmarkCodeBlock: (exchangeId: string, blockIndex: number) => void;
    onScrolledUpChange: (isUp: boolean) => void;
    onScrollPositionChange: (position: number) => void;
    /** 4B: Toggle collapse for a single assistant message. */
    onToggleCollapse: (messageId: string) => void;
}

const SCROLL_BOTTOM_THRESHOLD = 200;
const SCROLL_THROTTLE_MS = 150;

/**
 * SVG ribbon bookmark icon for code blocks.
 *
 * Matches the design spec — a clean flag/ribbon shape that works at 14×14.
 * Injected as innerHTML into dynamically created buttons (code blocks are
 * generated by markdown-it, not React components).
 */
const BOOKMARK_RIBBON_SVG = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg>`;

function MessageList({
                         messages,
                         isThinking,
                         isScrolledUp,
                         scrollPosition,
                         collapsedIds,
                         onConfirmCorrection,
                         onRequestCorrection,
                         onToggleStar,
                         onBookmarkCodeBlock,
                         onScrolledUpChange,
                         onScrollPositionChange,
                         onToggleCollapse,
                     }: MessageListProps) {
    const bottomRef = useRef<HTMLDivElement>(null);
    const listRef = useRef<HTMLDivElement>(null);
    const scrollThrottleRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    /**
     * Track whether we've applied the initial scroll position restore.
     * Prevents re-applying on every render — only applies once after
     * messages change (tab switch or history load).
     */
    const scrollRestoredRef = useRef(false);

    // ── R5: Scroll position restore on tab switch / history load ──
    // When messages change (tab switch loads new messages), restore the
    // saved scroll position. If position is 0 or very small, scroll to
    // bottom instead (new conversation or user was at bottom).
    useEffect(() => {
        if (!listRef.current || messages.length === 0) return;

        // Only restore once per message set change
        if (scrollRestoredRef.current) return;
        scrollRestoredRef.current = true;

        if (scrollPosition > SCROLL_BOTTOM_THRESHOLD) {
            // Restore saved position
            listRef.current.scrollTop = scrollPosition;
        } else {
            // At or near bottom — scroll to latest
            bottomRef.current?.scrollIntoView({ behavior: "auto" });
        }
    }, [messages, scrollPosition]);

    // Reset the restore flag when messages array reference changes
    // (i.e., a different tab's messages are now displayed)
    useEffect(() => {
        scrollRestoredRef.current = false;
    }, [messages]);

    // Auto-scroll only when user hasn't scrolled up
    useEffect(() => {
        if (!isScrolledUp) {
            bottomRef.current?.scrollIntoView({ behavior: "smooth" });
        }
    }, [messages.length, isThinking, isScrolledUp]);

    // Track scroll position and detect scroll-up state
    const handleScroll = useCallback(() => {
        if (!listRef.current) return;
        const el = listRef.current;
        const distFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;

        onScrolledUpChange(distFromBottom > SCROLL_BOTTOM_THRESHOLD);

        if (!scrollThrottleRef.current) {
            scrollThrottleRef.current = setTimeout(() => {
                scrollThrottleRef.current = null;
                onScrollPositionChange(el.scrollTop);
            }, SCROLL_THROTTLE_MS);
        }
    }, [onScrolledUpChange, onScrollPositionChange]);

    const scrollToBottom = useCallback(() => {
        bottomRef.current?.scrollIntoView({ behavior: "smooth" });
    }, []);

    // ── R5: Inject bookmark + copy buttons into code block headers ──
    // Star button removed from code blocks. Bookmark ribbon added instead.
    // The bookmark applies to the whole exchange, not the individual code block,
    // but we pass the block index for potential future per-block bookmarking.
    useEffect(() => {
        if (!listRef.current) return;

        const messageDivs = listRef.current.querySelectorAll(".ymm-message--assistant");
        messageDivs.forEach((messageDiv) => {
            // Find the exchangeId from the star button on this message
            const starBtn = messageDiv.querySelector(".ymm-exchange-star");
            const exchangeId = starBtn?.getAttribute("data-exchange-id") ?? null;

            const codeBlocks = messageDiv.querySelectorAll(".ymm-code-block");
            codeBlocks.forEach((block, index) => {
                block.setAttribute("data-block-index", String(index));
                if (exchangeId) {
                    block.setAttribute("data-exchange-id", exchangeId);
                }

                const container = block.querySelector(".ymm-code-actions");
                if (!container || container.querySelector(".ymm-code-copy")) return;

                // R5: Bookmark ribbon button — bookmarks the entire exchange
                if (exchangeId) {
                    const bookmarkBtn = document.createElement("button");
                    bookmarkBtn.className = "ymm-code-btn ymm-code-bookmark";
                    bookmarkBtn.innerHTML = BOOKMARK_RIBBON_SVG;
                    bookmarkBtn.title = "Bookmark this exchange";
                    container.appendChild(bookmarkBtn);
                }

                // Copy button — always visible
                const copyBtn = document.createElement("button");
                copyBtn.className = "ymm-code-btn ymm-code-copy";
                copyBtn.textContent = "Copy";
                copyBtn.title = "Copy code to clipboard";
                container.appendChild(copyBtn);
            });
        });
    }, [messages]);

    // Render Mermaid diagrams after markdown DOM insertion
    useEffect(() => {
        if (!listRef.current) return;
        renderMermaidBlocks(listRef.current);
    }, [messages]);

    // Event delegation for copy buttons, bookmark buttons, and star buttons
    const handleClick = useCallback(
        (e: React.MouseEvent<HTMLDivElement>) => {
            const target = e.target as HTMLElement;

            // ── Code copy ──
            if (target.classList.contains("ymm-code-copy")) {
                const codeBlock = target.closest(".ymm-code-block");
                if (!codeBlock) return;

                const encodedCode = codeBlock.getAttribute("data-code");
                if (!encodedCode) return;

                try {
                    const code = decodeURIComponent(escape(atob(encodedCode)));
                    if (navigator.clipboard && navigator.clipboard.writeText) {
                        navigator.clipboard.writeText(code).then(
                            () => showCopyFeedback(target, true),
                            () => fallbackCopy(code, target),
                        );
                    } else {
                        fallbackCopy(code, target);
                    }
                } catch (err) {
                    log.error("MessageList", "Failed to decode code for copy", { error: String(err) });
                }
                return;
            }

            // ── R5: Code block bookmark (STUBBED — coming soon) ──
            const bookmarkEl = target.classList.contains("ymm-code-bookmark")
                ? target
                : target.closest(".ymm-code-bookmark");
            if (bookmarkEl) {
                // TODO: Wire to code_bookmarks table when CodeBookmarkService is ready.
                // Show visible feedback that this feature is coming.
                const originalHTML = bookmarkEl.innerHTML;
                bookmarkEl.innerHTML = "Soon™";
                bookmarkEl.classList.add("ymm-code-bookmark--pending");
                setTimeout(() => {
                    bookmarkEl.innerHTML = originalHTML;
                    bookmarkEl.classList.remove("ymm-code-bookmark--pending");
                }, 1500);
                return;
            }

            // ── Exchange star toggle ──
            const starEl = target.classList.contains("ymm-exchange-star")
                ? target
                : target.closest(".ymm-exchange-star");
            if (starEl) {
                const exchangeId = starEl.getAttribute("data-exchange-id");
                if (exchangeId) onToggleStar(exchangeId);
                return;
            }
        },
        [onToggleStar, onBookmarkCodeBlock],
    );

    // ── Empty State ──────────────────────────────────────────────────

    if (messages.length === 0) {
        return (
            <div className="ymm-message-list ymm-message-list--empty">
                <div className="ymm-empty-state">
                    <p className="ymm-empty-state__title">Ready to chat</p>
                    <p className="ymm-empty-state__subtitle">
                        Send a message to start a conversation with your AI provider.
                    </p>
                </div>
            </div>
        );
    }

    // ── Message Rendering ────────────────────────────────────────────

    return (
        <div
            className="ymm-message-list"
            ref={listRef}
            onClick={handleClick}
            onScroll={handleScroll}
        >
            {messages.map((msg) => {
                if (msg.role === "system") {
                    return <SystemMessage key={msg.id} message={msg} />;
                }

                if (msg.role === "user") {
                    return (
                        <div key={msg.id} className="ymm-message ymm-message--user">
                            <div className="ymm-message__role">You</div>
                            <div className="ymm-message__content">{msg.content}</div>
                            <div className="ymm-message__timestamp">
                                {new Date(msg.timestamp).toLocaleTimeString()}
                            </div>
                        </div>
                    );
                }

                // Assistant message — with collapse/expand toggle
                const isCollapsed = collapsedIds.has(msg.id);

                return (
                    <div
                        key={msg.id}
                        className={
                            `ymm-message ymm-message--assistant`
                            + (msg.isError ? " ymm-message--error" : "")
                            + (isCollapsed ? " ymm-message--collapsed" : "")
                        }
                    >
                        {/* 4B: Header row — collapse toggle + role label (left), star (right) */}
                        <div className="ymm-message__header">
                            <div className="ymm-message__header-left">
                                <button
                                    className="ymm-collapse-toggle"
                                    onClick={() => onToggleCollapse(msg.id)}
                                    title={isCollapsed ? "Expand response" : "Collapse response"}
                                >
                                    {isCollapsed ? "▸" : "▾"}
                                </button>
                                <span className="ymm-message__role">Assistant</span>
                                {/* 4B: Preview snippet when collapsed — first ~60 chars of content */}
                                {isCollapsed && (
                                    <span className="ymm-collapse-preview">
                                        {msg.content.length > 60
                                            ? msg.content.substring(0, 60) + "…"
                                            : msg.content}
                                    </span>
                                )}
                            </div>
                            {msg.exchangeId && (
                                <button
                                    className={`ymm-exchange-star${msg.isStarred ? " ymm-exchange-star--active" : ""}`}
                                    data-exchange-id={msg.exchangeId}
                                    title={msg.isStarred ? "Remove from favourites" : "Add to favourites"}
                                >
                                    {msg.isStarred ? "★" : "☆"}
                                </button>
                            )}
                        </div>

                        {/* 4B: Content, correction, and timestamp hidden when collapsed */}
                        {!isCollapsed && (
                            <>
                                <div
                                    className="ymm-message__content ymm-markdown"
                                    dangerouslySetInnerHTML={{ __html: renderMarkdown(msg.content) }}
                                />

                                {msg.correctionAvailable && (
                                    <div className="ymm-message__correction">
                                        <button
                                            className="ymm-correction-btn ymm-correction-btn--confirm"
                                            onClick={onConfirmCorrection}
                                            title="The response looks correct"
                                        >
                                            ✓ Looks right
                                        </button>
                                        <button
                                            className="ymm-correction-btn ymm-correction-btn--reject"
                                            onClick={onRequestCorrection}
                                            title="The response was parsed incorrectly"
                                        >
                                            ✗ Not right
                                        </button>
                                    </div>
                                )}

                                <div className="ymm-message__timestamp">
                                    {new Date(msg.timestamp).toLocaleTimeString()}
                                </div>
                            </>
                        )}
                    </div>
                );
            })}

            {isThinking && <ThinkingIndicator />}

            <div ref={bottomRef} />

            {/* R4: Scroll-to-bottom floating button */}
            {isScrolledUp && (
                <button
                    className="ymm-scroll-to-bottom"
                    onClick={scrollToBottom}
                    title="Scroll to latest message"
                >
                    ↓
                </button>
            )}
        </div>
    );
}

// ═══════════════════════════════════════════════════════════════════════
//  CLIPBOARD HELPERS (unchanged from R2)
// ═══════════════════════════════════════════════════════════════════════

function showCopyFeedback(button: HTMLElement, success: boolean): void {
    const originalText = button.textContent;
    button.textContent = success ? "Copied!" : "Failed";
    button.classList.add(success ? "ymm-code-copy--success" : "ymm-code-copy--failed");
    setTimeout(() => {
        button.textContent = originalText;
        button.classList.remove("ymm-code-copy--success", "ymm-code-copy--failed");
    }, 1500);
}

function fallbackCopy(text: string, button: HTMLElement): void {
    try {
        const textarea = document.createElement("textarea");
        textarea.value = text;
        textarea.style.position = "fixed";
        textarea.style.opacity = "0";
        document.body.appendChild(textarea);
        textarea.select();
        const success = document.execCommand("copy");
        document.body.removeChild(textarea);
        showCopyFeedback(button, success);
    } catch {
        showCopyFeedback(button, false);
    }
}

export default MessageList;